name: cron job

on:
  push:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello world!"
      - run: echo "This is a secret ${{ secrets.SOME_SECRET }}" | base64
